# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-17 12:30
from __future__ import unicode_literals

import apps.accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(db_index=True, max_length=256, unique=True, verbose_name='E-mail')),
                ('user_name', models.CharField(blank=True, max_length=30, verbose_name='User name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Is staff')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Is superuser')),
                ('email_confirmed', models.BooleanField(default=False, verbose_name='Email confirmed')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Date joined')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserConfirmToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default=apps.accounts.models.random_word, max_length=24, verbose_name='Token uid')),
                ('token', models.CharField(default=apps.accounts.models.generate_token, max_length=50, verbose_name='Token')),
                ('reason', models.PositiveSmallIntegerField(choices=[(0, 'E-mail confirm'), (1, 'Password reset')], verbose_name='Reason')),
                ('used', models.BooleanField(default=False, verbose_name='Used')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tokens', to=settings.AUTH_USER_MODEL, verbose_name='Token owner')),
            ],
        ),
    ]
