# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-17 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400, verbose_name='Name')),
                ('slug', models.SlugField(max_length=400, verbose_name='Slug')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CourseRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400, verbose_name='Title')),
                ('slug', models.SlugField(max_length=400, verbose_name='Slug')),
                ('full_description', models.TextField(blank=True, null=True, verbose_name='Full description')),
                ('logo_image', models.ImageField(blank=True, null=True, upload_to='logos', verbose_name='Logo')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='covers', verbose_name='Cover Image')),
                ('type', models.CharField(blank=True, choices=[('offline', 'Offline'), ('online', 'Online'), ('both', 'Online and Offline')], max_length=100, null=True, verbose_name='Type')),
                ('cost', models.CharField(blank=True, choices=[('free', 'Free'), ('paid', 'Paid'), ('both', 'Free and Paid')], max_length=100, null=True, verbose_name='Cost')),
                ('phone1', models.CharField(blank=True, max_length=100, null=True, verbose_name='Phone 1')),
                ('phone2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Phone 2')),
                ('phone3', models.CharField(blank=True, max_length=100, null=True, verbose_name='Phone 3')),
                ('website', models.CharField(blank=True, max_length=4000, null=True, verbose_name='Website')),
                ('address', models.CharField(blank=True, max_length=400, null=True, verbose_name='Address')),
                ('email', models.CharField(blank=True, max_length=400, null=True, verbose_name='E-mail')),
                ('facebook', models.CharField(blank=True, max_length=4000, null=True, verbose_name='Facebook Page')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('cities', models.ManyToManyField(blank=True, related_name='eventsapp_by_city', to='hubsapp.City', verbose_name='Cities')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='CourseRecordImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='', upload_to='course_record_images', verbose_name='Image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400, verbose_name='Name')),
                ('slug', models.SlugField(max_length=400, verbose_name='Slug')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='courserecord',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='eventsapp_by_tag', to='hubsapp.Tag', verbose_name='Tags'),
        ),
    ]
