# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-30 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubsapp', '0002_eventrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventrecord',
            name='end_date',
            field=models.DateField(null=True, verbose_name='Event End Date'),
        ),
        migrations.AddField(
            model_name='eventrecord',
            name='start_date',
            field=models.DateField(null=True, verbose_name='Event Start Date'),
        ),
        migrations.AddField(
            model_name='eventrecord',
            name='start_time',
            field=models.TimeField(null=True, verbose_name='Event Start Time'),
        ),
        migrations.AlterField(
            model_name='courserecord',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='eventsapp_by_tag', to='hubsapp.Tag', verbose_name='Теги'),
        ),
    ]
