# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-15 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubsapp', '0003_auto_20161130_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventrecord',
            name='end_date',
            field=models.DateField(blank=True, default=None, verbose_name='Event End Date'),
            preserve_default=False,
        ),
    ]
