# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-15 23:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hubsapp', '0004_auto_20161216_0110'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseRecordImage',
            new_name='PostImage',
        ),
        migrations.RemoveField(
            model_name='courserecord',
            name='cities',
        ),
        migrations.RemoveField(
            model_name='courserecord',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='eventrecord',
            name='cities',
        ),
        migrations.RemoveField(
            model_name='eventrecord',
            name='tags',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='CourseRecord',
        ),
        migrations.DeleteModel(
            name='EventRecord',
        ),
    ]
