# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-19 10:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hubsapp', '0006_hub'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400, verbose_name='Title')),
                ('slug', models.SlugField(max_length=400, verbose_name='Slug')),
                ('leading_image', models.ImageField(blank=True, default='', upload_to='hub_images', verbose_name='Image')),
                ('short_text', models.TextField(verbose_name='Short Text')),
                ('full_text', models.TextField(verbose_name='Full Text')),
                ('published_date', models.DateTimeField(auto_now_add=True, verbose_name='Published Date')),
                ('changed_date', models.DateTimeField(auto_now_add=True, verbose_name='Changed Date')),
                ('status', models.CharField(default='Draft', max_length=200)),
                ('placement', models.CharField(default='Blog', max_length=200)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('hub', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hubsapp.Hub')),
            ],
            options={
                'db_table': 'post',
            },
        ),
    ]
